name: bookabook
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  carousel_pro: ^0.0.13
  shared_preferences: ^0.5.1+1
  cached_network_image: ^0.7.0
  flutter_swiper: ^1.1.6
  html: ^0.14.0+1



dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  fonts:
      - family: Raleway
        fonts:
          - asset: res/fonts/raleway/Raleway-Regular.ttf
          - asset: res/fonts/raleway/Raleway-Italic.ttf
            style: italic
  uses-material-design: true
  assets:
    - res/images/loginbg.png
    - res/placeholder.jpg